### ISSUE TITLE
Design Error Seite

### ISSUE THREAD

**Issue by mimischi** [PhysikOnline-FFM/gu-urlshorter#12]
Klickt man auf "Kürzen", ohne irgendeine Eingabe, so kommt man auf die Errorseite. Hier scheint eine andere CSS-Datei zugange zu sein, da z.B. der GU-Kopf im Hintergrund fehlt und auch die Footer-Leiste eine dunklere Farbe bekommt.

**Comment by svenk** [comment]
"It's not a bug, it's a feature" -- den Goethekopf im Hintergrund gibts nur auf der Startseite. Dafür sorgt Zeile 9ff in https://github.com/PhysikOnline-FFM/gu-urlshorter/blob/master/css/style.css#L9 (`body.index` matcht nur auf der Startseite, die `index` heißt).

Ist natürlich verbesserungswürdig, hab ja schon erwähnt, dass ich das Design für verbesserungswürdig halte.

**Comment by svenk** [comment]
Solang sich nicht jemand ein generell hübscheres Layout ausdenkt, finde ich das Aussehen von Fehler/Inhaltsseiten ausreichend.
