### ISSUE TITLE
Git Reports Issue

### ISSUE THREAD

**Issue by svenk** [PhysikOnline-FFM/gu-urlshorter#3]
Submitter: Tester
Email: test.testing@tester.de
Ich teste hier man die Gitreports-Anwendung, die es erlaubt, ohne Login/anonym neue Issues/Tickets zu erzeugen.

**Comment by svenk** [comment]
Okay, ist nicht so wirklich cool wenn man seinen eigenen Account damit verbindet. Da sollte ein Github-Platzhalteraccount für her.

**Comment by physikonline-feedback** [comment]
Okay, es gibt jetzt einen Account dafür, der auch mit https://gitreports.com/ verlinkt ist. Siehe https://elearning.physik.uni-frankfurt.de/projekt/ticket/1171 für die relevanten Daten.

**Comment by svenk** [comment]
Danke, lieber Tester!
