### ISSUE TITLE
Git Reports Issue

### ISSUE THREAD

**Issue by physikonline-feedback** [PhysikOnline-FFM/gu-urlshorter#5]
Submitter: Tester 2
Email: ich@ich.de
In Bezugnahme auf #3 möchte ich nun testen, was passiert, wenn man auf https://gitreports.com/issue/PhysikOnline-FFM/gu-urlshorter etwas abschickt.

**Comment by svenk** [comment]
Sieht gut aus!

**Comment by svenk** [comment]
Danke.
